// buildingCards data...
export const buildingCards = [
  {
    id: 1,
    number: "#1",
    name: "Mining Station",
    vp: 3,
    imageUrl: "/buildings/mining-station.png",
    effect: "Gain 2 crystal resources when activated",
    uses: 2,
  },
  {
    id: 2,
    number: "#2",
    name: "Research Lab",
    vp: 2,
    imageUrl: "/buildings/research-lab.png",
    effect: "Draw 1 extra card when mining",
    uses: 1,
  },
  {
    id: 3,
    number: "#3",
    name: "Defense Tower",
    vp: 4,
    imageUrl: "/buildings/defense-tower.png",
    effect: "Prevent 1 disaster per activation",
    uses: 3,
  },
  {
    id: 4,
    number: "#4",
    name: "Alien Embassy",
    vp: 5,
    imageUrl: "/buildings/alien-embassy.png",
    effect: "Trade with aliens for better resources",
    uses: 2,
  },
  {
    id: 5,
    number: "#5",
    name: "Power Plant",
    vp: 3,
    imageUrl: "/buildings/power-plant.png",
    effect: "Generate 2 energy per turn",
    uses: 1,
  },
  {
    id: 6,
    number: "#6",
    name: "Storage Facility",
    vp: 2,
    imageUrl: "/buildings/storage.png",
    effect: "Store up to 3 extra resources",
    uses: 2,
  },
  {
    id: 7,
    number: "#7",
    name: "Trading Post",
    vp: 3,
    imageUrl: "/buildings/trading-post.png",
    effect: "Exchange resources at better rates",
    uses: 2,
  },
  {
    id: 8,
    number: "#8",
    name: "Shield Generator",
    vp: 4,
    imageUrl: "/buildings/shield-gen.png",
    effect: "Protect against 2 disasters",
    uses: 3,
  },
  {
    id: 9,
    number: "#9",
    name: "Recycling Center",
    vp: 3,
    imageUrl: "/buildings/recycling.png",
    effect: "Convert waste into resources",
    uses: 1,
  },
  {
    id: 10,
    number: "#10",
    name: "Observatory",
    vp: 2,
    imageUrl: "/buildings/observatory.png",
    effect: "Peek at upcoming disasters",
    uses: 2,
  },
  {
    id: 11,
    number: "#11",
    name: "Teleporter",
    vp: 5,
    imageUrl: "/buildings/teleporter.png",
    effect: "Move resources between stations",
    uses: 3,
  },
  {
    id: 12,
    number: "#12",
    name: "Repair Bay",
    vp: 3,
    imageUrl: "/buildings/repair-bay.png",
    effect: "Fix damaged equipment",
    uses: 2,
  },
  {
    id: 13,
    number: "#13",
    name: "Command Center",
    vp: 4,
    imageUrl: "/buildings/command.png",
    effect: "Coordinate multiple actions",
    uses: 2,
  },
  {
    id: 14,
    number: "#14",
    name: "Resource Converter",
    vp: 3,
    imageUrl: "/buildings/converter.png",
    effect: "Transform resources freely",
    uses: 1,
  },
  {
    id: 15,
    number: "#15",
    name: "Scanner Array",
    vp: 2,
    imageUrl: "/buildings/scanner.png",
    effect: "Locate specific resources",
    uses: 1,
  },
  {
    id: 16,
    number: "#16",
    name: "Quantum Lab",
    vp: 5,
    imageUrl: "/buildings/quantum-lab.png",
    effect: "Double resource production",
    uses: 3,
  },
];
