const bonusCards = [
  {
    id: "card_1",
    name: "Starting Bonus #1",
    description: "This is starting bonus card #1.",
    effect: ["gold", "speed", "speed"],
    imageUrl: "/path/to/sample-card1-image.png",
    type: "bonus",
  },
  {
    id: "card_2",
    name: "Starting Bonus #2",
    description: "This is starting bonus card #2.",
    effect: ["initiative", "draw_1_card"],
    imageUrl: "/path/to/sample-card2-image.png",
    type: "bonus",
  },
  {
    id: "card_3",
    name: "Starting Bonus #3",
    description: "This is starting bonus card #3.",
    effect: ["speed", "speed", "ticket", "speed"],
    imageUrl: "/path/to/sample-card3-image.png",
    type: "bonus",
  },
  {
    id: "card_4",
    name: "Starting Bonus #4",
    description: "This is starting bonus card #4.",
    effect: ["initiative", "ticket", "coin"],
    imageUrl: "/path/to/sample-card4-image.png",
    type: "bonus",
  },
  {
    id: "card_5",
    name: "Starting Bonus #5",
    description: "This is starting bonus card #5.",
    effect: ["ticket", "initiative", "coin"],
    imageUrl: "/path/to/sample-card5-image.png",
    type: "bonus",
  },
  {
    id: "card_6",
    name: "Starting Bonus #6",
    description: "This is starting bonus card #6.",
    effect: ["guild", "coin"],
    imageUrl: "/path/to/sample-card6-image.png",
    type: "bonus",
  },
  {
    id: "card_7",
    name: "Starting Bonus #7",
    description: "This is starting bonus card #7.",
    effect: ["draw_1_card", "speed", "coin"],
    imageUrl: "/path/to/sample-card7-image.png",
    type: "bonus",
  },
  {
    id: "card_8",
    name: "Starting Bonus #8",
    description: "This is starting bonus card #8.",
    effect: ["initiative", "initiative", "coin"],
    imageUrl: "/path/to/sample-card8-image.png",
    type: "bonus",
  },
  {
    id: "card_9",
    name: "Starting Bonus #9",
    description: "This is starting bonus card #9.",
    effect: ["speed", "initiative", "ticket"],
    imageUrl: "/path/to/sample-card9-image.png",
    type: "bonus",
  },
  {
    id: "card_10",
    name: "Starting Bonus #10",
    description: "This is starting bonus card #10.",
    effect: ["ticket", "draw_1_card"],
    imageUrl: "/path/to/sample-card10-image.png",
    type: "bonus",
  },
  {
    id: "card_11",
    name: "Starting Bonus #11",
    description: "This is starting bonus card #11.",
    effect: ["speed", "draw_1_card", "coin"],
    imageUrl: "/path/to/sample-card11-image.png",
    type: "bonus",
  },
  {
    id: "card_12",
    name: "Starting Bonus #12",
    description: "This is starting bonus card #12.",
    effect: ["dungeon", "coin"],
    imageUrl: "/path/to/sample-card12-image.png",
    type: "bonus",
  },
  {
    id: "card_13",
    name: "Starting Bonus #13",
    description: "This is starting bonus card #13.",
    effect: ["gold", "initiative"],
    imageUrl: "/path/to/sample-card13-image.png",
    type: "bonus",
  },
  {
    id: "card_14",
    name: "Starting Bonus #14",
    description: "This is starting bonus card #14.",
    effect: ["draw_1_epic"],
    imageUrl: "/path/to/sample-card14-image.png",
    type: "bonus",
  },
  {
    id: "card_15",
    name: "Starting Bonus #15",
    description: "This is starting bonus card #15.",
    effect: ["speed", "initiative", "coin_2"],
    imageUrl: "/path/to/sample-card15-image.png",
    type: "bonus",
  },
  {
    id: "card_16",
    name: "Starting Bonus #16",
    description: "This is starting bonus card #16.",
    effect: ["ticket", "draw_1_card"],
    imageUrl: "/path/to/sample-card16-image.png",
    type: "bonus",
  },
  {
    id: "card_17",
    name: "Starting Bonus #17",
    description: "This is starting bonus card #17.",
    effect: ["guild", "speed"],
    imageUrl: "/path/to/sample-card17-image.png",
    type: "bonus",
  },
  {
    id: "card_18",
    name: "Starting Bonus #18",
    description: "This is starting bonus card #18.",
    effect: ["ticket", "coin", "ticket"],
    imageUrl: "/path/to/sample-card18-image.png",
    type: "bonus",
  },
  {
    id: "card_19",
    name: "Starting Bonus #19",
    description: "This is starting bonus card #19.",
    effect: ["gold", "coin_2"],
    imageUrl: "/path/to/sample-card19-image.png",
    type: "bonus",
  },
  {
    id: "card_20",
    name: "Starting Bonus #20",
    description: "This is starting bonus card #20.",
    effect: ["draw_1_card", "coin_2"],
    imageUrl: "/path/to/sample-card20-image.png",
    type: "bonus",
  },
  {
    id: "card_21",
    name: "Starting Bonus #21",
    description: "This is starting bonus card #21.",
    effect: ["draw_1_epic"],
    imageUrl: "/path/to/sample-card21-image.png",
    type: "bonus",
  },
  {
    id: "card_22",
    name: "Starting Bonus #22",
    description: "This is starting bonus card #22.",
    effect: ["initiative", "gold"],
    imageUrl: "/path/to/sample-card22-image.png",
    type: "bonus",
  },
  {
    id: "card_23",
    name: "Starting Bonus #23",
    description: "This is starting bonus card #23.",
    effect: ["ticket", "speed", "coin_2"],
    imageUrl: "/path/to/sample-card23-image.png",
    type: "bonus",
  },
  {
    id: "card_24",
    name: "Starting Bonus #24",
    description: "This is starting bonus card #24.",
    effect: ["ticket", "speed", "coin_2"],
    imageUrl: "/path/to/sample-card24-image.png",
    type: "bonus",
  },
];

const passiveCards = [
  {
    id: "card_25",
    name: "Golden Gamble",
    effect:
      "If you gain 3x [ticket] in a single turn, gain [gold]. If you gain 4x [ticket] in a single turn, gain 2x [gold]. Only one can be activated.",
    type: "passive",
  },
  {
    id: "card_26",
    name: "Guild Shortcut",
    effect:
      "Once per turn when you move in [dungeon], you may pay [coin_3] to move in [guild].",
    type: "passive",
  },
  {
    id: "card_27",
    name: "Stealth Tactics",
    effect:
      "You don't pay to players if you have lower [initiative] when you step on their location.",
    type: "passive",
  },
  {
    id: "card_28",
    name: "Swift Explorer",
    effect:
      "Once per turn, if you moved 3 or more spaces in any [dungeon]/[guild], gain [vp_2].",
    type: "passive",
  },
  {
    id: "card_29",
    name: "Master Adventurer",
    effect:
      "If you finish both [dungeon] and [guild] in the same turn, gain [ticket] [ticket] [gold].",
    type: "passive",
  },
  {
    id: "card_30",
    name: "Golden Rush",
    effect:
      "Whenever you use [gold] [gold], gain [speed] [speed] for the next turn.",
    type: "passive",
  },
  {
    id: "card_31",
    name: "Lap of Glory",
    effect:
      "Whenever you make a full circle and pass the 1st location, gain [coin] [speed].",
    type: "passive",
  },
  {
    id: "card_32",
    name: "Speed Burst",
    effect:
      "Once per turn, if you used more than 4 [speed] in the same turn, gain [initiative].",
    type: "passive",
  },
  {
    id: "card_33",
    name: "High Status",
    effect:
      "If a player gains [initiative] and had the same as you, gain [coin_3].",
    type: "passive",
  },
  {
    id: "card_34",
    name: "Master Builder",
    effect:
      "Whenever you [build] 2 times in a turn, gain [initiative] [speed] [coin].",
    type: "passive",
  },
  {
    id: "card_35",
    name: "Wealth Accumulation",
    effect:
      "At the end of your turn if you have 7 or more [coin], gain [ticket].",
    type: "passive",
  },
  {
    id: "card_36",
    name: "Epic Trade",
    effect:
      "Whenever you [draw_1_epic], you may pay [ticket] [ticket] to gain [gold] [coin_3].",
    type: "passive",
  },
];

const heroPowers = [
  {
    id: "card_37",
    name: "Shadow Strike",
    effect:
      "Once per turn, steal 1x [coin] from another player when you gain [initiative].",
    type: "heropower",
    uses: 3,
    hero: "Ravenblade",
  },
  {
    id: "card_38",
    name: "Guardian's Blessing",
    effect:
      "If you defend against an attack, gain [gold] and 1x [initiative] for the next turn.",
    type: "heropower",
    uses: 4,
    hero: "Ironclad",
  },
  {
    id: "card_39",
    name: "Blazing Speed",
    effect:
      "You may pay 2x [coin] to move an extra 3 spaces in one turn. Can be used once per round.",
    type: "heropower",
    uses: 2,
    hero: "Flameheart",
  },
  {
    id: "card_40",
    name: "Mystic Insight",
    effect:
      "Once per turn, reveal the top 3 cards of the deck. Draw 1 and shuffle the rest back.",
    type: "heropower",
    uses: 5,
    hero: "Aetheris",
  },
  {
    id: "card_41",
    name: "Golden Touch",
    effect:
      "If you collect 3x [coin] in a turn, gain an additional [gold]. Can be triggered once per round.",
    type: "heropower",
    uses: 4,
    hero: "Aurion",
  },
  {
    id: "card_42",
    name: "Fortune's Favor",
    effect:
      "When you use [ticket], gain 1x [initiative] and 1x [speed] for your next move.",
    type: "heropower",
    uses: 3,
    hero: "Lunara",
  },
  {
    id: "card_43",
    name: "Warrior's Fury",
    effect:
      "If you defeat a monster, gain [speed] and 2x [coin] instantly. Can be used twice per game.",
    type: "heropower",
    uses: 2,
    hero: "Thornbreaker",
  },
  {
    id: "card_44",
    name: "Arcane Shield",
    effect:
      "Once per turn, negate any negative effect targeting you. Gain 1x [vp] for each negation.",
    type: "heropower",
    uses: 5,
    hero: "Eldrasil",
  },
];

const tradeCards = [
  {
    id: "card_45",
    name: "Trade #1",
    effect: "Gain [coin_3]",
    type: "trade",
    subtype: "gain",
  },
  {
    id: "card_46",
    name: "Trade #2",
    effect: "Gain [coin_2] [speed]",
    type: "trade",
    subtype: "gain",
  },
  {
    id: "card_47",
    name: "Trade #3",
    effect: "Gain [speed] [speed] [coin]",
    type: "trade",
    subtype: "gain",
  },
  {
    id: "card_48",
    name: "Trade #4",
    effect: "Gain [gold]",
    type: "trade",
    subtype: "gain",
  },
  {
    id: "card_49",
    name: "Trade #5",
    effect: "Gain [ticket] [speed]",
    type: "trade",
    subtype: "gain",
  },
  {
    id: "card_50",
    name: "Trade #6",
    effect: "Gain [ticket] [coin]",
    type: "trade",
    subtype: "gain",
  },
  {
    id: "card_51",
    name: "Trade #7",
    effect: "Gain [initiative] [coin]",
    type: "trade",
    subtype: "gain",
  },
  {
    id: "card_52",
    name: "Trade #8",
    effect: "Gain [initiative] [speed]",
    type: "trade",
    subtype: "gain",
  },
  {
    id: "card_53",
    name: "Trade #9",
    effect: "Gain [dungeon]",
    type: "trade",
    subtype: "gain",
  },
  {
    id: "card_54",
    name: "Trade #10",
    effect: "Gain [guild]",
    type: "trade",
    subtype: "gain",
  },
  {
    id: "card_55",
    name: "Trade #11",
    effect: "Gain [coin_2], If you have 3+ [initiative]: [coin] [speed]",
    type: "trade",
    subtype: "gain",
  },
  {
    id: "card_56",
    name: "Trade #12",
    effect: "Gain [coin] [speed], If you have 3+ [guild]: [coin_2]",
    type: "trade",
    subtype: "gain",
  },
  {
    id: "card_57",
    name: "Trade #13",
    effect: "Gain [ticket], If you have 3+ [dungeon]: [ticket]",
    type: "trade",
    subtype: "gain",
  },
  {
    id: "card_58",
    name: "Trade #14",
    effect: "Gain [initiative], If you have an [upgraded market]: [initiative]",
    type: "trade",
    subtype: "gain",
  },
  {
    id: "card_59",
    name: "Trade #15",
    effect: "Gain [coin_2], If you have 3+ [initiative]: [coin_2]",
    type: "trade",
    subtype: "gain",
  },
  {
    id: "card_60",
    name: "Trade #16",
    effect: "Gain [coin] [speed], If you have 3+ [guild]: [speed] [speed]",
    type: "trade",
    subtype: "gain",
  },
  {
    id: "card_61",
    name: "Trade #17",
    effect: "Gain [ticket], If you have 3+ [dungeon]: [speed] [coin]",
    type: "trade",
    subtype: "gain",
  },
  {
    id: "card_62",
    name: "Trade #18",
    effect: "Gain [initiative], If you have an [upgraded market]: [ticket]",
    type: "trade",
    subtype: "gain",
  },
  {
    id: "card_63",
    name: "Trade #19",
    effect: "[coin_1] [->] [ticket] [ticket]",
    type: "trade",
    subtype: "convert",
  },
  {
    id: "card_64",
    name: "Trade #20",
    effect: "[coin_1] [->] [ticket] [initiative]",
    type: "trade",
    subtype: "convert",
  },
  {
    id: "card_65",
    name: "Trade #21",
    effect: "[coin_1] [->] [gold] [speed]",
    type: "trade",
    subtype: "convert",
  },
  {
    id: "card_66",
    name: "Trade #22",
    effect: "[coin_1] [->] [dungeon] [speed]",
    type: "trade",
    subtype: "convert",
  },
  {
    id: "card_67",
    name: "Trade #23",
    effect: "[coin_1] [->] [guild] [speed]",
    type: "trade",
    subtype: "convert",
  },
  {
    id: "card_68",
    name: "Trade #24",
    effect: "[coin_1] [->] [draw_1_card] [speed]",
    type: "trade",
    subtype: "convert",
  },
  {
    id: "card_69",
    name: "Trade #25",
    effect: "[speed] [->] [draw_1_card] [coin]",
    type: "trade",
    subtype: "convert",
  },
  {
    id: "card_70",
    name: "Trade #26",
    effect: "[speed] [->] [ticket] [initiative]",
    type: "trade",
    subtype: "convert",
  },
  {
    id: "card_71",
    name: "Trade #27",
    effect: "[speed] [->] [ticket] [ticket]",
    type: "trade",
    subtype: "convert",
  },
  {
    id: "card_72",
    name: "Trade #28",
    effect: "[speed] [->] [initiative] [initiative]",
    type: "trade",
    subtype: "convert",
  },
  {
    id: "card_73",
    name: "Trade #29",
    effect: "[speed] [->] [gold] [coin]",
    type: "trade",
    subtype: "convert",
  },
  {
    id: "card_74",
    name: "Trade #30",
    effect: "[speed] [->] [guild] [coin]",
    type: "trade",
    subtype: "convert",
  },
  {
    id: "card_75",
    name: "Trade #31",
    effect: "[speed] [->] [dungeon] [coin]",
    type: "trade",
    subtype: "convert",
  },
  {
    id: "card_76",
    name: "Trade #32",
    effect: "[coin_1] [speed] [->] [gold] [ticket]",
    type: "trade",
    subtype: "convert",
  },
  {
    id: "card_77",
    name: "Trade #33",
    effect: "[coin_1] [speed] [->] [ticket] [initiative] [coin]",
    type: "trade",
    subtype: "convert",
  },
  {
    id: "card_78",
    name: "Trade #34",
    effect: "[coin_1] [speed] [->] [draw_1_card] [initiative]",
    type: "trade",
    subtype: "convert",
  },
  {
    id: "card_79",
    name: "Trade #35",
    effect: "[speed] [speed] [->] [gold] [draw_1_card]",
    type: "trade",
    subtype: "convert",
  },
  {
    id: "card_80",
    name: "Trade #36",
    effect: "[speed] [speed] [->] [draw_1_card] [ticket] [coin]",
    type: "trade",
    subtype: "convert",
  },
  {
    id: "card_81",
    name: "Trade #37",
    effect: "[speed] [speed] [->] [dungeon] [ticket]",
    type: "trade",
    subtype: "convert",
  },
  {
    id: "card_82",
    name: "Trade #38",
    effect: "[coin_2] [->] [guild] [ticket]",
    type: "trade",
    subtype: "convert",
  },
  {
    id: "card_83",
    name: "Trade #39",
    effect: "[coin_2] [->] [guild] [initiative]",
    type: "trade",
    subtype: "convert",
  },
  {
    id: "card_84",
    name: "Trade #40",
    effect: "[coin_2] [->] [ticket] [draw_1_card] [coin]",
    type: "trade",
    subtype: "convert",
  },
  {
    id: "card_85",
    name: "Trade #41",
    effect: "[ticket] [->] [guild]",
    type: "trade",
    subtype: "convert",
  },
  {
    id: "card_86",
    name: "Trade #42",
    effect: "[ticket] [->] [dungeon]",
    type: "trade",
    subtype: "convert",
  },
  {
    id: "card_87",
    name: "Trade #43",
    effect: "[ticket] [->] [speed] [speed] [draw_1_card]",
    type: "trade",
    subtype: "convert",
  },
  {
    id: "card_88",
    name: "Trade #44",
    effect: "[initiative] [->] [coin_2] [draw_1_card]",
    type: "trade",
    subtype: "convert",
  },
  {
    id: "card_89",
    name: "Trade #45",
    effect:
      "[coin_1] [speed] [speed] [->] [gold] [ticket], If you have 5+ [initiative]: [coin] [speed] [speed]",
    type: "trade",
    subtype: "convert",
  },
  {
    id: "card_90",
    name: "Trade #46",
    effect:
      "[coin_2] [speed] [->] [ticket] [initiative] [coin], If you have 5+ [guild]: [coin_3]",
    type: "trade",
    subtype: "convert",
  },
  {
    id: "card_91",
    name: "Trade #47",
    effect:
      "[coin_3] [->] [gold] [initiative], If you have 5+ [dungeon]: [guild]",
    type: "trade",
    subtype: "convert",
  },
  {
    id: "card_92",
    name: "Trade #48",
    effect:
      "[speed] [speed] [speed] [->] [gold] [gold], If you have 2+ [upgraded markets]: [draw_1_card]",
    type: "trade",
    subtype: "convert",
  },
  {
    id: "card_93",
    name: "Trade #49",
    effect:
      "[gold] [->] [gold] [ticket] [coin], If you have 5+ [initiative]: [coin_2]",
    type: "trade",
    subtype: "convert",
  },
  {
    id: "card_94",
    name: "Trade #50",
    effect:
      "[ticket] [coin] [->] [dungeon] [ticket], If you have 5+ [guild]: [initiative] [speed]",
    type: "trade",
    subtype: "convert",
  },
  {
    id: "card_95",
    name: "Trade #51",
    effect:
      "[ticket] [speed] [->] [guild] [ticket], If you have 5+ [guild]: [dungeon]",
    type: "trade",
    subtype: "convert",
  },
  {
    id: "card_96",
    name: "Trade #52",
    effect:
      "[initiative] [coin] [->] [guild] [initiative], If you have 2+ [upgraded market]: [gold]",
    type: "trade",
    subtype: "convert",
  },
  {
    id: "card_97",
    name: "Trade #53",
    effect:
      "[ticket] [speed] [->] [ticket] [ticket] [initiative], If you have 5+ [speed]: [draw_1_card]",
    type: "trade",
    subtype: "convert",
  },
  {
    id: "card_98",
    name: "Trade #54",
    effect:
      "[coin_1] [speed] [speed] [->] [guild], If you have 4+ [tickets]: [ticket] [gold]",
    type: "trade",
    subtype: "convert",
  },
  {
    id: "card_99",
    name: "Trade #55",
    effect:
      "[ticket] [coin] [->] [dungeon], If you have built 3+ [markets]: [draw_1_card]",
    type: "trade",
    subtype: "convert",
  },
  {
    id: "card_100",
    name: "Trade #56",
    effect:
      "[coin_2] [speed] [->] [gold] [coin], If you have built 3+ [markets]: [dungeon]",
    type: "trade",
    subtype: "convert",
  },
  {
    id: "card_101",
    name: "Trade #57",
    effect: "[coin_3] [->] [gold] [speed], If you have 3+ [gold]: [guild]",
    type: "trade",
    subtype: "convert",
  },
];

const dungeonGame = {
  id: "game1",
  slug: "wild-dungeoneers",
  name: "Wild Dungeoneers",
  description:
    "An adventurous journey through wild dungeons, filled with thrilling encounters and challenges.",
  cards: [...bonusCards, ...passiveCards, ...heroPowers, ...tradeCards],
  expansions: [],
  types: {
    "type-bonus": { name: "Starting Bonus" },
    "type-passive": { name: "Passive" },
    "type-heropower": { name: "Hero Power" },
    "type-trade": { name: "Trade" },
  },
  methodsConfig: [
    {
      method: "draw_type-bonus",
      name: "Draw Starting Bonus",
      type: "type-bonus",
    },
    {
      method: "draw_type-passive",
      name: "Draw Passive Card",
      type: "type-passive",
    },
    {
      method: "draw_type-heropower",
      name: "Draw Passive Card",
      type: "type-heropower",
    },
    {
      method: "draw_type-trade",
      name: "Draw Trade Card",
      type: "type-trade",
    },
  ],
};
export const staticGames = [dungeonGame];
